version: '3.8'

services:
  tempel-game:
    build:
      context: .
      dockerfile: server.Dockerfile
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
